import "./globals.css";

import { Metadata } from "next";

import { ApolloClientProvider, NextAuthProvider } from "./providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ApolloClientProvider>
          <NextAuthProvider>{children}</NextAuthProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
